### ISSUE TITLE
[Bug]: the integration seems broken at this point 

### ISSUE THREAD

**Issue by OsiMood** [klacol/homeassistant-clage_homeserver#11]
### What happened?

Hassfest is not validating anymore and some errors with the latest version of HA

### Version

latest

### What version of Home Assistant are you seeing the problem on?

2024.4.0

### Relevant log output

2024-04-06 07:53:16.909 ERROR (MainThread) [homeassistant.components.sensor] Error adding entity sensor.clagehomeserver_clage_dsx_heater_id for domain sensor with platform clage_homeserver
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 580, in _async_add_entities
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 881, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1332, in add_to_platform_finish
    await self.async_internal_added_to_hass()
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 302, in async_internal_added_to_hass
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: Entity sensor.clagehomeserver_clage_dsx_heater_id cannot be added as the entity category is set to config
2024-04-06 07:53:16.931 ERROR (MainThread) [homeassistant.components.sensor] Error adding entity sensor.clagehomeserver_clage_dsx_heater_busid for domain sensor with platform clage_homeserver
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 580, in _async_add_entities
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 881, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1332, in add_to_platform_finish
    await self.async_internal_added_to_hass()
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 302, in async_internal_added_to_hass
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: Entity sensor.clagehomeserver_clage_dsx_heater_busid cannot be added as the entity category is set to config
2024-04-06 07:53:16.934 ERROR (MainThread) [homeassistant.components.sensor] Error adding entity sensor.clagehomeserver_clage_dsx_heater_name for domain sensor with platform clage_homeserver
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 580, in _async_add_entities
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 881, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1332, in add_to_platform_finish
    await self.async_internal_added_to_hass()
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 302, in async_internal_added_to_hass
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: Entity sensor.clagehomeserver_clage_dsx_heater_name cannot be added as the entity category is set to config
2024-04-06 07:53:16.936 ERROR (MainThread) [homeassistant.components.sensor] Error adding entity sensor.clagehomeserver_clage_dsx_heater_connected for domain sensor with platform clage_homeserver
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 580, in _async_add_entities
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 881, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1332, in add_to_platform_finish
    await self.async_internal_added_to_hass()
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 302, in async_internal_added_to_hass
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: Entity sensor.clagehomeserver_clage_dsx_heater_connected cannot be added as the entity category is set to config
2024-04-06 07:53:16.941 ERROR (MainThread) [homeassistant.components.sensor] Error adding entity sensor.clagehomeserver_clage_dsx_heater_status_tp1 for domain sensor with platform clage_homeserver
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 580, in _async_add_entities
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 881, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1332, in add_to_platform_finish
    await self.async_internal_added_to_hass()
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 302, in async_internal_added_to_hass
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: Entity sensor.clagehomeserver_clage_dsx_heater_status_tp1 cannot be added as the entity category is set to config
2024-04-06 07:53:16.946 ERROR (MainThread) [homeassistant.components.sensor] Error adding entity sensor.clagehomeserver_clage_dsx_heater_status_tp2 for domain sensor with platform clage_homeserver
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 580, in _async_add_entities
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 881, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1332, in add_to_platform_finish
    await self.async_internal_added_to_hass()
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 302, in async_internal_added_to_hass
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: Entity sensor.clagehomeserver_clage_dsx_heater_status_tp2 cannot be added as the entity category is set to config
2024-04-06 07:53:16.949 ERROR (MainThread) [homeassistant.components.sensor] Error adding entity sensor.clagehomeserver_clage_dsx_heater_status_tp3 for domain sensor with platform clage_homeserver
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 580, in _async_add_entities
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 881, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1332, in add_to_platform_finish
    await self.async_internal_added_to_hass()
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 302, in async_internal_added_to_hass
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: Entity sensor.clagehomeserver_clage_dsx_heater_status_tp3 cannot be added as the entity category is set to config

**Comment by klacol** [comment]
This is, what `Validate with hassfest` says:

> validate[SERVICES] Service set_temperature has no name and is not in the translations file
> validateProcess completed with exit code 1.
> validate[TRANSLATIONS] config.title key has been moved out of config and into the root of strings.json. Starting Home Assistant 0.109 you only need to define this key in the root if the title needs to be different than the name of your integration in the manifest.
> 2 errors and 1 warning


I am not sure, waht this exactly means

**Comment by klacol** [comment]
Ok, that has worked
![image](https://github.com/klacol/homeassistant-clage_homeserver/assets/10479772/2b1267d6-b571-44ec-a938-c4a310a01623)

**Comment by klacol** [comment]
ok, green again. Please test, if it works,

**Comment by OsiMood** [comment]
Thank you sir! Will try shortly!

**Comment by OsiMood** [comment]
All working. Many thanks, really appreciated
