### ISSUE TITLE
[Bug]: Error in Log:  'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by klacol** [klacol/homeassistant-clage_homeserver#15]
### What happened?

This error is reported in the log.

### Version

latest

### What version of Home Assistant are you seeing the problem on?

2024.4.3

### Relevant log output

```shell
ogger: custom_components.clage_homeserver
Quelle: helpers/update_coordinator.py:315
Integration: CLAGE Homeserver (Dokumentation, Probleme)
Erstmals aufgetreten: 10:01:34 (11 Vorkommnisse)
Zuletzt protokolliert: 10:05:00

Unexpected error fetching clage_homeserver data: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 315, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 271, in _async_update_data
    return await self.update_method()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/clage_homeserver/__init__.py", line 129, in fetch_states
    await self._hass.async_add_executor_job(homeserver.requestStatus)
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/clage_homeserver/clage_homeserver.py", line 403, in requestStatus
    response = ClageHomeServerMapper().mapApiStatusResponse(status)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/clage_homeserver/clage_homeserver.py", line 29, in mapApiStatusResponse
    heater = status.get('devices')[NUMBER_OF_CONNECTED_HEATERS-1]
             ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
```

**Comment by holgergrote** [comment]
I also updated the integraion to the newest version (via HACS with Version 2024.4.3)
I did not get the warnings after a restart. I will check the next days the logs if ther will be something loged.

**Comment by holgergrote** [comment]
I checked the logs again. Still no issues with the integration.

**Comment by klacol** [comment]
This must be fixed in the lib: https://github.com/klacol/clage_homeserver
