### ISSUE TITLE
Error when updating from input

### ISSUE THREAD

**Issue by OsiMood** [klacol/homeassistant-clage_homeserver#4]
Hi trying to use your automation to change the water temp from the input
```
- id: 'set_based_on_input'
  alias: 'clage_homeserver: set temperature based on input'
  description: ''
  trigger:
  - entity_id: input_number.boiler_temp
    platform: state
  condition: []
  action:
  - data_template:
      homeserver_name: clage_dsx
      heater_id: 2016FFEE22
      temperature: '{{ states(''input_number.boiler_temp'') }}'
    service: clage_homeserver.set_temperature
```
Unfortunately, got this in the log
```
Logger: homeassistant.components.automation.clage_homeserver_set_temperature_based_on_input
Source: custom_components/clage_homeserver/__init__.py:230
Integration: Automation ([documentation](https://www.home-assistant.io/integrations/automation), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+automation%22))
First occurred: 21:12:03 (2 occurrences)
Last logged: 21:12:03

clage_homeserver: set temperature based on input: Error executing script. Unexpected error for call_service at pos 1: free variable 'homeserver_name' referenced before assignment in enclosing scope
While executing automation automation.clage_homeserver_set_temperature_based_on_input
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 447, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 680, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1713, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1750, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/config/custom_components/clage_homeserver/__init__.py", line 230, in async_handle_set_temperature
    homeserver = homeservers[homeserver_name]
NameError: free variable 'homeserver_name' referenced before assignment in enclosing scope
```

Not sure what I am doing wrong, I set the server name in the DSX rest is really copy/paste

**Comment by OsiMood** [comment]
Line 231 of "__init__.py", should be changed from
`                homeserver = homeservers[homeserver_name]`
to
`                homeserver = homeservers[homeserver_name_input]`

**Comment by klacol** [comment]
Thanks for you feedback. Could you test your fix on your HA installation?

**Comment by OsiMood** [comment]
I have and it is working for me on my instance

I also made another mode on the clage_homeserver.py pip extension

**Comment by klacol** [comment]
Great, any PR is welcome

**Comment by OsiMood** [comment]
👍
