### ISSUE TITLE
homeassistant.setup: Platform not found 

### ISSUE THREAD

**Issue by klacol** [klacol/homeassistant-clage_homeserver#8]
### What happened?

The integration does not start after boot.

### Version

1.0.3 (Edge)

### What browsers are you seeing the problem on?

Microsoft Edge

### Relevant log output

```shell
Logger: homeassistant.setup
Source: setup.py:320
First occurred: 09:02:30 (2 occurrences)
Last logged: 09:02:30

Unable to prepare setup for platform clage_homeserver.sensor: Platform not found (Exception importing custom_components.clage_homeserver.sensor).
```

### Code of Conduct

- [X] klacol/clage_homeserver#51

**Comment by klacol** [comment]
> Logger: homeassistant.loader
> Source: custom_components/clage_homeserver/sensor.py:58
> Integration: CLAGE Homeserver ([documentation](https://github.com/klacol/homeassistant-clage_homeserver), [issues](https://github.com/klacol/homeassistant-clage_homeserver/issues))
> First occurred: 09:02:30 (2 occurrences)
> Last logged: 09:02:30
> 
> Unexpected exception importing platform custom_components.clage_homeserver.sensor
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/loader.py", line 722, in get_platform
>     cache[full_name] = self._import_platform(platform_name)
>   File "/usr/src/homeassistant/homeassistant/loader.py", line 739, in _import_platform
>     return importlib.import_module(f"{self.pkg_path}.{platform_name}")
>   File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
>   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
>   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
>   File "/config/custom_components/clage_homeserver/sensor.py", line 58, in <module>
>     entity_category=EntityCategory.DIAGNOSTICT,
>   File "/usr/local/lib/python3.10/enum.py", line 437, in __getattr__
>     raise AttributeError(name) from None
> AttributeError: DIAGNOSTICT

**Comment by klacol** [comment]
Ok, fixed with https://github.com/klacol/homeassistant-clage_homeserver/commit/ccaae3181f15289fee73fc4b6486c9107d7e335e and https://github.com/klacol/homeassistant-clage_homeserver/commit/a7515c1f19bfadd82e862b6453d00e5d9f05dbae.
